name: Import Schedule Daily & Score Games Hourly

on:
  schedule:
    - cron: "0 11 * * *"
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Import schedule (daily)
        if: ${{ github.event.schedule == '0 11 * * *' || github.event_name == 'workflow_dispatch' }}
        run: |
          curl -sS -X POST "$API_BASE/api/cron/import-schedule" \
            -H "x-cron-secret: $CRON_SECRET"
      - name: Score updates (every 30 mins)
        if: ${{ github.event.schedule == '*/30 * * * *' || github.event_name == 'workflow_dispatch' }}
        run: |
          curl -sS -X POST "$API_BASE/api/cron/score?season=2025" \
            -H "x-cron-secret: $CRON_SECRET"
    env:
      API_BASE: ${{ secrets.API_BASE }}
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
